Configure DAC for remote connections

diff --git a/eng/pipelines/common/templates/steps/configure-sql-server-macos-step.yml b/eng/pipelines/common/templates/steps/configure-sql-server-macos-step.yml
--- a/eng/pipelines/common/templates/steps/configure-sql-server-macos-step.yml
+++ b/eng/pipelines/common/templates/steps/configure-sql-server-macos-step.yml
@@ -64,5 +64,15 @@ steps:
       rm -f $SQLCMD_ERRORS
     fi
 
+    echo "Configuring Dedicated Administer Connections to allow remote connections..."
+    sqlcmd -S 0.0.0.0 -No -U sa -P $MSSQL_SA_PW -Q "sp_configure 'remote admin connections', 1; RECONFIGURE;"
+    if [ $? = 1 ]
+    then
+      echo "Error configuring DAC for remote access."
+      exit $errstatus
+    else
+      echo "Configuration complete."
+    fi
+
   displayName: 'Configure SQL Server [macOS]'
   condition: ${{parameters.condition }}
