testing

diff --git a/eng/pipelines/common/templates/steps/configure-sql-server-macos-step.yml b/eng/pipelines/common/templates/steps/configure-sql-server-macos-step.yml
--- a/eng/pipelines/common/templates/steps/configure-sql-server-macos-step.yml
+++ b/eng/pipelines/common/templates/steps/configure-sql-server-macos-step.yml
@@ -35,13 +35,34 @@ steps:
  
     docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=$MSSQL_SA_PW" -p 1433:1433 --name sql1 --hostname sql1 -d mcr.microsoft.com/mssql/server:2022-latest
  
-    sleep 5
+    sleep 10
 
     docker ps -a
 
     docker exec sql1 /opt/mssql-tools18/bin/sqlcmd \
     -S localhost -No -U SA -P $MSSQL_SA_PW \
     -Q "SELECT @@VERSION"
+
+    # Connect to server and get the version:
+    counter=1
+    errstatus=1
+    while [ $counter -le 5 ] && [ $errstatus = 1 ]
+    do
+      echo Waiting for SQL Server to start...
+      sleep 3
+      sqlcmd -S 0.0.0.0 -No -U sa -P $MSSQL_SA_PW -Q "SELECT @@VERSION" 2>/dev/null
+      errstatus=$?
+      ((counter++))
+    done
+
+    # Display error if connection failed:
+    if [ $errstatus = 1 ]
+    then
+      echo Cannot connect to SQL Server, installation aborted
+      exit $errstatus
+    else
+      sqlcmd -S 0.0.0.0 -No -U sa -P $MSSQL_SA_PW -Q "SELECT @@VERSION"
+    fi
 
   displayName: 'Configure SQL Server [macOS]'
   condition: ${{parameters.condition }}
